version: "3.8"

services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
        - 3001:3001
      volumes:
        - .:/app
        - '/app/node_modules'
      depends_on: 
        - mysql

    mysql:
        image: mysql:5.7
        environment: 
          - MYSQL_DATABASE=MCC
          - MYSQL_USER=tester
          - MYSQL_PASSWORD=password
          - MYSQL_ROOT_PASSWORD=password